language: python
python:
- "3.6"
# setup environment
addons:
  postgresql: "9.4"
env:
- DJANGO_VERSION=2.1.3
# install dependencies
install:
- pip install -r requirements.txt
# run test scripts

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test 

