# Generated by Django 2.1.3 on 2018-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terreno', '0005_poligono_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poligono',
            name='coordenadas_puntos',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
