# Generated by Django 2.1.3 on 2018-11-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20181104_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='estado',
            field=models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default='Activo', max_length=50),
        ),
    ]
